const TYPES = module.exports.TYPES = {
  VAR: 'VAR',
  CLASS: 'CLASS',
  METHOD: 'METHOD',
  CONSTR: 'CONSTR',
}

const ACTION_NAMES = module.exports.ACTION_NAMES = {
  GETTER: 'GETTER',
  SETTER: 'SETTER',
  GETTER_SETTER: 'GETTER_SETTER',
  GET_SET: 'GET_SET',
  CONSTRUCTOR: 'CONSTRUCTOR',
  CONSTRUCTOR_PARAM: 'CONSTRUCTOR_PARAM',
  OVERLOAD: 'OVERLOAD',
}

module.exports.ACTION_MAPPING = {
  [TYPES.VAR]: [
    ACTION_NAMES.GETTER,
    ACTION_NAMES.SETTER,
    ACTION_NAMES.GETTER_SETTER,
    ACTION_NAMES.GET_SET,
    ACTION_NAMES.CONSTRUCTOR_PARAM,
  ],
  [TYPES.CLASS]: [
    ACTION_NAMES.CONSTRUCTOR,
  ],
  [TYPES.CONSTR]: [
    ACTION_NAMES.OVERLOAD,
  ],
  [TYPES.METHOD]: [
    ACTION_NAMES.OVERLOAD,
  ]
}
